{
 "title": "BigBlueButton Server Instance (node_exporter)",
 "tags": [
  "BigBlueButton",
  "prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bbb_exporter, job)"
   },
   {
    "name": "job_node_exporter",
    "label": "Job node_exporter",
    "query": "label_values(node_cpu_seconds_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(node_network_transmit_bytes_total, device)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bbb_exporter{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Type of Users Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "bbb_meetings_listeners{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Listeners"
    },
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Voice"
    },
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "CPU Utilization vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"$job_node_exporter\", instance=\"$instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{job=\"$job_node_exporter\", mode=\"idle\",instance=~\"$instance\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{job=\"$job_node_exporter\", instance=~\"$instance\"}) by (cpu))",
     "legendFormat": "CPU Utlization"
    },
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Bandwidth vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job_node_exporter\", instance=\"$instance\", device=\"$interface\"}[1m])*8",
     "legendFormat": "Bandwidth {{device}} (receive)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job_node_exporter\", instance=\"$instance\", device=\"$interface\"}[1m])*8",
     "legendFormat": "Bandiwidth {{device}} (transmit)"
    },
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Max Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Selected timeframe"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}[1w])",
     "legendFormat": "Since 1 week"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Video Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Video participants"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_recordings_processing{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Unprocessed"
    },
    {
     "expr": "bbb_recordings_published{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Published"
    },
    {
     "expr": "bbb_recordings_unpublished{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Unpublished"
    },
    {
     "expr": "bbb_recordings_deleted{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job_node_exporter\", instance=\"$instance\"} - node_filesystem_avail_bytes{job=\"$job_node_exporter\", instance=\"$instance\"}) / node_filesystem_size_bytes{job=\"$job_node_exporter\", instance=\"$instance\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "graph",
   "description": "Requires `RECORDINGS_METRICS_READ_FROM_DISK` to be enabled on the BigBlueButton Exporter",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Recordings " }
   ],
   "targets": [
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Recordings Unprocessed "
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participant_clients{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Histograms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap of Room Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "bbb_room_participants_bucket{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Listeners Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "bbb_room_listeners_bucket{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Voice Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "bbb_room_voice_participants_bucket{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Video Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "bbb_room_video_participants_bucket{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton API Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processing\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processed\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=published\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=unpublished\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=deleted\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings deleted"
    }
   ]
  }
 ]
}
{
 "title": "BigBlueButton All Servers",
 "tags": [
  "BigBlueButton",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bbb_exporter, job)"
   },
   {
    "name": "job_node_exporter",
    "label": "Job node_exporter",
    "query": "label_values(node_cpu_seconds_total, job)"
   },
   {
    "name": "job_netdata",
    "label": "Job Netdata",
    "query": "label_values(netdata_system_cpu_percentage_average, job)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(node_network_address_assign_type, device)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bbb_api_up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bbb_exporter{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_room_participants_gcount{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Participants per server",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum(bbb_meetings_participant_clients{job=\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Participants for Selected Timeframe",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Participants Origin",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants_origin{job=\"$job\"}",
     "legendFormat": "{{server}} - {{name}}"
    }
   ]
  },
  {
   "title": "CPU Utlization ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job_node_exporter\"}[5m])) by (instance)) * 100",
     "legendFormat": "{{instance}} (node_exporter)"
    },
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\", job=\"$job_netdata\"}) by (instance)",
     "legendFormat": "{{instance}} (Netdata)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job_node_exporter\"} - node_memory_MemAvailable_bytes{job=\"$job_node_exporter\"}) by (instance)",
     "legendFormat": "{{instance}} (node_exporter)"
    },
    {
     "expr": "(sum(netdata_system_ram_MiB_average{job=\"$job_netdata\"}) by (instance) - sum(netdata_mem_available_MiB_average{job=\"$job_netdata\"}) by (instance)) * 1024 * 1024",
     "legendFormat": "{{instance}} (Netdata)"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job_node_exporter\", device=\"$interface\"}[1m])*8",
     "legendFormat": "{{instance}} receive ({{device}}) (node_exporter)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job_node_exporter\", device=\"$interface\"}[1m])*8",
     "legendFormat": "{{instance}} sent ({{device}}) (node_exporteer)"
    },
    {
     "expr": "abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", family=\"$interface\"})",
     "legendFormat": "{{instance}} {{dimension}} ({{family}}) (Netdata)"
    }
   ]
  },
  { "title": "Recordings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Storage Utilization",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job_node_exporter\"} - node_filesystem_avail_bytes{job=\"$job_node_exporter\"}) / node_filesystem_size_bytes{job=\"$job_node_exporter\"}"
    }
   ]
  },
  {
   "title": "Recordings Processing",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_processing{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 54 },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_unprocessed{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
    }
   ]
  },
  {
   "title": "Recordings Published",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_published{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
    }
   ]
  },
  {
   "title": "Recordings Deleted",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 59 },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_deleted{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
    }
   ]
  },
  {
   "title": "Recordings Unpublished",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "label_replace(bbb_recordings_unpublished{job=\"$job\"}, \"name\", \"$1\", \"instance\", \"([a-zA-Z0-9-]*).*:.*\")"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "graph",
   "description": "Requires `RECORDINGS_METRICS_READ_FROM_DISK` to be enabled on the BigBlueButton Exporter",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Recordings " }
   ],
   "targets": [
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Heatmap of Room Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Listeners Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_listeners_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Voice Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_voice_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Video Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_video_participants_bucket{job=\"$job\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton API Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "s", "label": "Resonse Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getMeetings\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processing\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processed\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=published\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=unpublished\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=deleted\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings deleted"
    }
   ]
  }
 ]
}
{
 "title": "BBB resources monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running BBB Servers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"bbb\",instance=~\".*:9100\"})",
     "legendFormat": "Servers"
    }
   ]
  },
  {
   "title": "CPUs per Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"bbb\", mode='system'}) by (instance)",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "RAM per server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"bbb\"} / 1000000000",
     "legendFormat": "{{ instance}}"
    }
   ]
  }
 ]
}