apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-resolver
  namespace: jitsi
data:
  resolv.conf: |-
    nameserver 10.96.0.10
    nameserver 8.8.8.8
    search jitsi.svc.cluster.local svc.cluster.local cluster.local 
