apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
  labels:
    purpose: jibri-shared-deployment
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atnus0001.atena.io
    path: "/media/nfs"
