apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jibri-volume-claim
  namespace: jitsi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: 'standard'
  selector:
    matchLabels:
      purpose: jibri-shared-deployment
