apiVersion: v1
kind: Service
metadata:
  namespace: jitsi
  labels:
    service: jibri
  name: jibri
spec:
  clusterIP: None
  ports:
  - name: "jibri"
    port: 8001
    targetPort: 80
  selector:
    k8s-app: jibri

