apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jibri-one
  labels:
    component: jibri
  namespace: jitsi
spec:
  serviceName: jibri-one
  replicas: 1
  selector:
    matchLabels:
      component: jibri
  template:
    metadata:
      labels:
        component: jibri
    spec:
      hostAliases:
        - ip: '1.1.1.1'
          hostnames:
            - example.com
      securityContext:
        fsGroup: 63
      initContainers:
        - name: init-set
          image: xuxant/init-container
          command: 
            - /tmp/copyfile.sh
          volumeMounts:
            - name: home-dir
              mountPath: /home/jibri
      containers:
        - name: jibri
          image: docker.io/jitsi/jibri
          resources:
            limits:
              memory: '4G'
              cpu: '2'
            requests:
              memory: '2G'
              cpu: '1'
          envFrom:
            - configMapRef:
                name: jibri-env
          volumeMounts:
            - name: dns-resolver
              mountPath: '/etc/resolv.conf'
              subPath: resolv.conf
              readOnly: false
            - name: jibri-recorder
              mountPath: /config/recordings
            - name: jibri-logs
              mountPath: /config/logs
            - name: snd
              mountPath: /dev/snd
            - name: shm
              mountPath: /dev/shm
            - name: finalize-sh
              mountPath: /config/finalize.sh
              subPath: finalize.sh
            - name: home-dir
              mountPath: /home/jibri
            - name: assound-1
              mountPath: '/home/jibri/.asoundrc'
              subPath: .asoundrc
              readOnly: false
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_ADMIN
      volumes:
        - name: dns-resolver
          configMap:
            name: dns-resolver
        - name: jibri-recorder
          persistentVolumeClaim:
            claimName: jibri-volume-claim
        - name: jibri-logs
          emptyDir: {}
        - name: snd
          hostPath:
            path: /dev/snd
        - name: finalize-sh
          configMap:
            name: finalize-sh
            defaultMode: 0777
        - name: home-dir
          emptyDir: {}
        - name: shm
          hostPath:
            path: /dev/shm
