apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/coreos/kube-prometheus?ref=release-0.5
- monitoring/
- metacontroller/
- cert-manager/
- ingress-nginx/
- jitsi/
