apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  namespace: jitsi
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: {{username}}
    password: {{password}}
