apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb2-udp
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30301
  selector:
    k8s-app: jvb2
